feat: 增加less lint

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,16 +1,18 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
-print_colored() {
-  color_code="$1"
-  text="$2"
-  printf "\033[${color_code}m%s\033[0m\n" "$text"
+run_check() {
+  command_name="$1"
+  success_message="$2"
+  fail_message="$3"
+
+  if $command_name; then
+    printf "\033[32m%s\033[0m\n" "$success_message"
+  else
+    printf "\033[31m%s\033[0m\n" "$fail_message"
+    exit 1
+  fi
 }
 
-# 运行 lint 并直接检查其退出状态
-if npm run lint; then
-  print_colored 32 "Linting successful" # 32 是绿色的 ANSI 代码
-else
-  print_colored 31 "Linting failed!" # 31 是红色的 ANSI 代码
-  exit 1
-fi
+run_check "npm run lint" "ESLint check successful" "ESLint check failed!"
+run_check "npm run stylelint" "Stylelint check successful" "Stylelint check failed!"
